name: 'FTP Deploy Action'
description: 'Deploy files to an FTP server'
inputs:
  ftp-server:
    description: 'FTP server URL'
    required: true
  ftp-username:
    description: 'FTP server username'
    required: true
  ftp-password:
    description: 'FTP server password'
    required: true
  local-dir:
    description: 'Local directory to upload'
    required: true
  git-ftp-args:
    description: 'Additional arguments for git-ftp'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
